# Generated by Django 4.2.20 on 2026-05-14 18:25

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nr_lista', models.TextField(blank=True, db_column='Nr Lista', null=True)),
                ('id_lista', models.TextField(blank=True, db_column='ID Lista', null=True)),
                ('locatie', models.TextField(blank=True, db_column='Locatie', null=True)),
                ('lungime', models.FloatField(blank=True, db_column='Lungime', null=True)),
                ('nr_cabluri', models.IntegerField(blank=True, db_column='Nr Cabluri', null=True)),
                ('nava', models.IntegerField(blank=True, db_column='Nava', null=True)),
                ('tragator', models.TextField(blank=True, db_column='Tragator', null=True)),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('trimis', models.BooleanField(blank=True, db_column='Trimis', default=False, null=True)),
                ('data_trimisa', models.DateField(blank=True, db_column='Data trimisa', null=True)),
                ('dosar', models.TextField(blank=True, db_column='Dosar', null=True)),
                ('rework', models.BooleanField(blank=True, db_column='Rework', default=False, null=True)),
                ('data_rework', models.DateField(blank=True, db_column='Data Rework', null=True)),
                ('ore_rework', models.FloatField(blank=True, db_column='Ore Rework', null=True)),
            ],
            options={
                'db_table': 'list963',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StocUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='Read-only')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizator',
                'verbose_name_plural': 'Utilizatori',
                'db_table': 'stoc_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
